### ISSUE TITLE
Parsing JSON

### ISSUE THREAD

**Issue by brianburridge** [Steve998/Assignments#17]
_This is assignment 17 and is due on Feb 03, 2015._
- Read about [HTTP](http://en.wikipedia.org/wiki/Hypertext_Transfer_Protocol)
- Read review on [using JSON in Ruby](https://hackhands.com/ruby-read-json-file-hash/)
- Look thru some [JSON Examples](http://json.org/example)
- Copy assignment 15 and modify to now read in questions from a JSON file
- This means you need to create a JSON file of you questions
- Read and parse the JSON into an array so the rest of the app remains the same

**Comment by brianburridge** [comment]
Hi Steve. I'm not able to test this because the questions.json isn't in GitHub.

It all looks good, but before I close it out I'd like to see the JSON and be able to run it. Thanks.

**Comment by Steve998** [comment]
OK Done

**Comment by brianburridge** [comment]
:+1:
