### ISSUE TITLE
Movie Querying script

### ISSUE THREAD

**Issue by brianburridge** [Steve998/Assignments#18]
_This is assignment 18 and is due on Feb 04, 2015._
- http://developer.rottentomatoes.com/
- Use Rotten Tomato's movie querying script to create a command line app which prompts the user for a movie title
- Using the entered movie title, search via the API for the movie's synopsis and output to the user
- If more than one movie comes back, show all the movie title matches with their synopsis

**Comment by brianburridge** [comment]
There isn't a requirement in this assignment to write the response from the Rotten Tomato API into a file.  You can parse the response directly without all the other File reading and writing. Take that out and ensure your app still runs and then I'll take another look at it.

**Comment by Steve998** [comment]
Done

**Comment by brianburridge** [comment]
Nice and simple

:clap:
