### ISSUE TITLE
Using Gems and ActiveSupport

### ISSUE THREAD

**Issue by brianburridge** [Steve998/Assignments#19]
_This is assignment 20 and is due on Feb 04, 2015._
- Note: Please check in your Gemfile and Gemfile.lock
- write a Ruby script that uses the Rails ActiveSupport gem, installed via a Gemfile and bundler
- the script should do the following when run:

1) Show the date of the beginning of the current week
2) Show what the date will be in 30 days
3) Show what day of the week today's date will fall on next year
4) Show what day of the week the user's birthday will be on this year
5) Using the String class, pluralize a singular word the user enters and show the singular for a plural word the user enters
6) Using the String class, truncate a phrase the user enters to 20 letters
7) Using the Array class, convert an array of three words to a sentence with one command
- You'll need the following Rails extensions that come with ActiveSupport:
- http://api.rubyonrails.org/v4.0.3/classes/Date.html
- http://api.rubyonrails.org/v4.0.3/classes/String.html
- http://api.rubyonrails.org/v4.0.3/classes/Array.html
- http://api.rubyonrails.org/v4.0.3/classes/Numeric.html

**Comment by brianburridge** [comment]
For the first one, it should return the _date_ of the beginning of the week instead of the day of the week.

For the 4th requirement, it should prompt the user for their birthday and then show what day it will be on this year.

I don't see pluralizing a word, the second part of number 5.

All the rest look good. Just those three changes needed.

**Comment by Steve998** [comment]
OK I made the changes and put into GitHub

**Comment by brianburridge** [comment]
:+1:
