### ISSUE TITLE
Invoicing

### ISSUE THREAD

**Issue by brianburridge** [Steve998/Assignments#23]
_This is assignment 23 and is due on Feb 09, 2015._
- Create an InvoiceItem class and an Invoice class (two classes in two separate files)
- The InvoiceItem class should have the following attributes: product_name, sale_price, quantity, tax percentage
- The invoice class should have a getter and setter for an attribute called: _items_ to hold an array of all the InvoiceItems
- Create an instance method in Invoice that will calculate a total of all it's invoice items
- Use reject or select methods in order to remove any InvoiceItem objects that have a zero quantity
- Create an instance method in Invoice to sum up the invoice items and get a total
- Ask the user to enter in the attributes for each invoice item, hitting ENTER on product name when done
- With each invoice item entered, create the object and add it to the collection of invoice items within a single Invoice object.
- Then output each line item.
- Show a sub-total without the tax, then a line item for the tax, then the total.
- Bonus: make the invoice look like a real world invoice in the terminal

**Comment by Steve998** [comment]
Done Thanks

**Comment by brianburridge** [comment]
:+1:
