### ISSUE TITLE
More work with classes, getters and setters (in class, pairing)

### ISSUE THREAD

**Issue by brianburridge** [Steve998/Assignments#26]
_This is assignment 25b and is due on Feb 10, 2015._
- Design and code a Blog and Post class.
- These classes should model a system where a user can create a blog, which will have posts.
- A Blog can have a name, a user_name, and the collection of posts
- A Post can have a name, a summary, the body of the post, the published date, and a word count.
- Since both a blog and a post MUST have a name, override the initializer so that when an object of either class is created, a name must be supplied.

**Comment by Steve998** [comment]
Done

**Comment by brianburridge** [comment]
Hey @Steve998 . I can't accept this, or really even read it, until it comes a lot closer to the Ruby style guide. At the very least, Blog and Post need some serious formatting love.

**Comment by Steve998** [comment]
I pushed a folder a25b that has the updated files in it. These should match Tom's files for this exercise. Thanks

**Comment by brianburridge** [comment]
:+1:
