### ISSUE TITLE
Multipe models, Scaffolding, and Heroku Deploys

### ISSUE THREAD

**Issue by brianburridge** [Steve998/Assignments#36]
_This is assignment 35 and is due on Feb 23, 2015._
- Create a new Rails app, in it's own folder (not within the previous _Assignments_ folder)
- This new Rails app should have three models. Two of them should have scaffolds. They should all have associations, so pick three models that are related in some way.
- Ensure all associations can be set within your Rails app views (no longer just in the console)
- On the index view of a parent model, show the count of children it has (the has_many relationship). Example: how many books does that library have?
- Add a _Procfile_ to your app with this line: `web: bundle exec thin start -p $PORT` (note: this is to get it working on Heroku)
- Add the following to your Gemfile (please read the comments to remind yourself why each Gem is necessary):
  
  ```
  # User the 'thin' server instead of the default webrick
  gem 'thin'
  
  # Use postgres and the Heroku rails gem for Heroku
  group :production do
    gem 'rails_12factor'
  end
  ```
- Deploy to Heroku
- When you submit the assignment, paste the URL to your Heroku app in a comment within this issue.

**Comment by Steve998** [comment]
Heroku Link
https://mighty-beyond-3271.herokuapp.com/

very basic and not very pretty but works

**Comment by brianburridge** [comment]
:+1:
