### ISSUE TITLE
Seed Data and Image Uploading

### ISSUE THREAD

**Issue by brianburridge** [Steve998/Assignments#37]
_This is assignment 36 and is due on Feb 24, 2015._
- Add some seed data to assignment 35 using the Faker gem.
- Add image upload support to your Rails app from assignment 35, using [CarrierWave gem](https://github.com/carrierwaveuploader/carrierwave).
- You can add image uploads to any existing models in that app.
- For this assignment, use _file_ storage.
- Your user should be able to browse for a local image and upload it along with your other model attributes in the form.
- The uploaded images should show on both the index page (thumbnail size) and the show page (a larger size).
- Feel free to experiment with sizes and versions.
- Please include the URL to your Github repo for this app in a comment in this issue.
- Note: do not deploy this to Heroku yet

**Comment by Steve998** [comment]
Link 
https://github.com/Steve998/assignment35
I created the github repo for assignment 36. When when doing the "git remote add origin git@github.com:Steve998/assignment36.git" the response was "fatal: remote origin already exists." When I did the "git push" it pushed it to the assignment 35 repo. Not sure what I missed.

**Comment by brianburridge** [comment]
:+1:
