### ISSUE TITLE
Math and Comparisons

### ISSUE THREAD

**Issue by brianburridge** [Steve998/Assignments#4]
_This assignment is due on Jan 28, 2015._

Use the following code to create a Ruby file and run it. The file can be run either by `ruby filename` or, if you choose, you can set the executable bit (`chmod +x filename`) and add a shebang.

```
puts 3 > 4
puts (3 * 2) > 10
puts 2 == 3
puts (1 > 0) && (2 <= 1)
puts 2 != 2
puts (14 <= 10) || (2 >= 3)
puts 10 % 2 == 1
puts (10 ** 2) == 1000
puts 1000 / 300 > 4
```

Now change the code above so that when you run it, all the equations are true.

Please create a gist of the final code and paste the url of the gist in an issue comment.

**Comment by Steve998** [comment]
https://gist.github.com/Steve998/ef1b10d5b0085d142cb0

**Comment by brianburridge** [comment]
:+1:
