### ISSUE TITLE
Adding a User model and scoping your app to the current user

### ISSUE THREAD

**Issue by brianburridge** [Steve998/Assignments#40]
_This is assignment 39 and is due on Feb 26, 2015._
- Modify the app from assignment 36-38, to have a User model
- Also, modify any models that should be scoped to a User, to belong to a user object
- Only show the user's records when in that context
- Create a User guest record in the seed file
- Default your app to always use that User
- Modify at least one model's create to be automatically associated with that User when it's created.
- Deploy to Heroku
- Paste the link to your Heroku app in a comment here for my review

**Comment by Steve998** [comment]
Heroku link 

https://mighty-beyond-3271.herokuapp.com/

git hub repo link 
https://github.com/Steve998/assignment-39-Add-user-model-to-app

**Comment by brianburridge** [comment]
The relationship between company and user isn't setup quite right. You currently have it described as a many to many in Rails but setup as a belongs_to in the database with a foreign key.

I don't see where you have done bullets 3 and 6.

**Comment by Steve998** [comment]
I pushed the changes to this link 

https://github.com/Steve998/assignment44-Restrict-Active-Admin-user

**Comment by brianburridge** [comment]
We also talked about you making a change to satisfy the 3rd bullet. Did you do that?

You can skip bullet six since it doesn't apply to your app.

**Comment by Steve998** [comment]
Made the changes so the companies displayed in the index are only the companies for the current user
Link to the changes:

https://github.com/Steve998/assignment44-Restrict-Active-Admin-user

**Comment by brianburridge** [comment]
Bingo!
