### ISSUE TITLE
Using ActiveAdmin for fully customizable, but quick, back-end admins

### ISSUE THREAD

**Issue by brianburridge** [Steve998/Assignments#41]
_This is assignment 40 and is due on Feb 26, 2015._
- Add [ActiveAdmin](https://github.com/activeadmin/activeadmin) to your current application
- Review the [documentation](https://github.com/activeadmin/activeadmin/blob/master/docs/0-installation.md)
- Create an active admin resource for every model in your app
- Do some customization
- Ensure all forms save and allow the user to set the relationships
- Deploy to Heroku
- Paste the link to your Heroku app in a comment here for my review

**Comment by Steve998** [comment]
heroku link for active admin
https://mighty-beyond-3271.herokuapp.com/admin/

**Comment by brianburridge** [comment]
There are a few issues with both ActiveAdmin and your models (which I didn't notice until I reviewed this one). Let's review the code tomorrow and get this straightened out.

**Comment by brianburridge** [comment]
Removing the completed tag for now. Once you make the changes we just discussed, you can add it again to notify me to check it.

**Comment by Steve998** [comment]
heroku link 
https://mighty-beyond-3271.herokuapp.com/

made several changes in the model and database and made the appropriate changes for the app

**Comment by brianburridge** [comment]
The models look soooo much better now!

There is only one tiny thing missing. In the ActiveAdmin for Orders, it does not let me set the customer. (hint: permit params). Once that's fixed this will be done.

**Comment by Steve998** [comment]
heroku link 

https://git.heroku.com/mighty-beyond-3271.git

OK Fixed that issue so shou;d be ready to go. (Thanks for the help too)

**Comment by brianburridge** [comment]
super :exclamation:
