### ISSUE TITLE
Custom Rake Tasks

### ISSUE THREAD

**Issue by brianburridge** [Steve998/Assignments#46]
_This is assignment 45 and is due on Mar 05, 2015._
- Read about [Rake tasks in Rails](http://guides.rubyonrails.org/command_line.html#rake)
- Create a custom rake task for your Pinterest app that will output the current count of all your models. Example:
  
  Teams: 4
  Users: 10
  Books: 15
  Authors: 2
  Movies: 1

**Comment by Steve998** [comment]
Push to GitHub lib/tasks/count.rake

**Comment by brianburridge** [comment]
Just an fyi: you don't need to have the `.to_s` on the end to convert the count to a string. Ruby will do that since you are appending it to another string.

So just this will work fine:

```ruby
puts 'The number of Companies is ' + Company.count
```

Works good though, so closing it. :+1:

**Comment by brianburridge** [comment]
No idea what I was thinking with that last comment, so, disregard!
