### ISSUE TITLE
Debugging a Rails Application

### ISSUE THREAD

**Issue by brianburridge** [Steve998/Assignments#49]
_This is assignment 48 and is due on Mar 11, 2015._
- Read about ri [Up and Running With Ruby Interactive](http://samuelmullen.com/2012/01/up-and-running-with-ruby-interactive-ri/), [5 Reasons You Should Use ri To Read Ruby Documentation](http://www.jstorimer.com/blogs/workingwithcode/7766081-5-reasons-you-should-use-ri-to-read-ruby-documentation)
- Try [Dash](http://kapeli.com/dash)
- Try [OmniRef](https://www.omniref.com/)
- Sign up to use the [Suncoast Dev Slack](http://suncoast.io)
- Install the [better_errors gem](https://github.com/charliesome/better_errors) in your Pinterest application. Create an error to see how it works.
- Read about the [Rails logger](http://guides.rubyonrails.org/debugging_rails_applications.html) and implement some lines in your controller. Output an instance variable using the `.inspect` method to the log. Paste the section of your log file in a comment in this issue. In an issue comment direct me to where you have added the logger statements. (Yes, in this case you can check logger statements in).
- Read about using the [pry console debugger](https://github.com/nixme/pry-debugger) and try it in a controller action.

**Comment by Steve998** [comment]
I put the logger.debug in the Company app in the companies.controller. The logger.debug has "DEBUG THIS LINE" to find it easier. The .inspect is on the next line in the same companies.controller for the @companies which is displayed below in the snip. 

Here is the log file snip: 
Started GET "/companies" for 127.0.0.1 at 2015-03-13 16:51:29 -0400
Processing by CompaniesController#index as HTML
DEBUG THIS LINE
Company(id: integer, name: string, bio: text, created_at: datetime, updated_at: datetime, image: string)

**Comment by brianburridge** [comment]
:+1:
