### ISSUE TITLE
ActiveRecord Query Interface

### ISSUE THREAD

**Issue by brianburridge** [Steve998/Assignments#51]
_This is assignment 50 and is due on Mar 12, 2015._
- Reread the [ActiveRecord Query Interface doc](http://guides.rubyonrails.org/active_record_querying.html)
- Create a new Rails app, and the four models mentioned in the guide (with proper migrations): Client, Address, Order, Role
- Create just one controller (call it anything), with one action
- Make that one action the root
- Within that controller, try all the query samples from the query guide, section 1.1 (skipping the batches) and sections 2, 3, 4, and 5 and put a comment above as to why each is used.
- The view can just say "See controller" (no output is expected)
- No other views or scaffolds are required.
- You many need to create some basic seed data for the four models.
- Don't go overboard and make this too complex.

**Comment by brianburridge** [comment]
Can you link me to the app you put this in please?

**Comment by Steve998** [comment]
Heroku link 

https://radiant-hamlet-1788.herokuapp.com/

Thanks

**Comment by brianburridge** [comment]
I meant the github repo so I Can see the code. :)

**Comment by brianburridge** [comment]
I found it.

**Comment by brianburridge** [comment]
:+1:
