### ISSUE TITLE
GitHub Flow, Branching, Favorite Movies

### ISSUE THREAD

**Issue by brianburridge** [Steve998/Assignments#52]
_This is assignment 51 and is due on Mar 16, 2015._
- Review what a [counter cache](http://guides.rubyonrails.org/association_basics.html) is (just section 4.1.2.3).
- Review [The Flow](https://guides.github.com/introduction/flow/)
- Read [Git Branching](http://git-scm.com/book/ca/v1/Git-Branching), sections 3.1 - 3.5
- Watch this [90 minute video](https://vimeo.com/108798680) on using Git. The password is _ironyard_.
- Clone my [movie_ratings app](https://github.com/theironyard-tampabay/movie_ratings)
- Create a new branch for this app, so you can add new functionality to it.
- In this branch, add a MovieFavorite model to the app to keep track of a user's favorite movies. In the existing movie controller app, also add a 'favorite' and 'unfavorite' action to create or destroy an appropriate record showing the movie has been favorited by the logged in user.
- The option to favorite a movie should be next to the current option to rate a movie. Note: like the Instagram app, no form is needed. Once favorite, the link should change to unfavorite.
- Also add a new action and view under account controller to show all the user's favorite movies. Add a link to this new page onto the nav.
- When the functionality is added and committed to the new branch, push the new branch to your GitHub repo, and place a pull request.
- Copy the PR link into a comment here. Do not accept the PR so I can see it pending. I will review, and provide feedback.

**Comment by Steve998** [comment]
git hub link 

https://github.com/theironyard-tampabay/movie_ratings/pull/7

**Comment by brianburridge** [comment]
@Steve998 there are several issues with this one. Let's sit down tomorrow afternoon and go through it together.

**Comment by Steve998** [comment]
OK I got this working again

**Comment by brianburridge** [comment]
Left a couple of small pieces of feedback. Address those and I'll be able to close this out.

**Comment by Steve998** [comment]
I removed the name from the favorites list and also removed the obsolete moviefavorites controller. 
Pushed to github should be ready now.
Thanks for the feedback

**Comment by brianburridge** [comment]
I don't think your changes were pushed out to github. It's still showing the last commit you pushed was from a day ago.

**Comment by brianburridge** [comment]
:+1:
