### ISSUE TITLE
Rails Native Authentication

### ISSUE THREAD

**Issue by brianburridge** [Steve998/Assignments#54]
_This is assignment 53 and is due on Mar 18, 2015._
- Review [using cookies in Rails](http://api.rubyonrails.org/classes/ActionDispatch/Cookies.html)
- Review [Rails sessions](http://guides.rubyonrails.org/action_controller_overview.html#session)
- Review [has_secure_password](http://api.rubyonrails.org/classes/ActiveModel/SecurePassword/ClassMethods.html)
- Add real user authentication to your Pinterest app
- User sign up, sign in, sign out
- Adjust current_user method in application controller to use the signed in user from the session

**Comment by Steve998** [comment]
The user authentication is now working in the Recipe app

**Comment by brianburridge** [comment]
@Steve998 authentication isn't quite working yet. There is no authentication that I could see for the user to sign in with their user and password, and nothing to force a user to sign in to user the site. Half way there. :)

**Comment by brianburridge** [comment]
@Steve998 we just worked on this together. I'm closing this out. Please be sure you fully understand what we just did to secure your app with the `before_action` and the `skip_before_action`.
