### ISSUE TITLE
Ruby Koans, First Half

### ISSUE THREAD

**Issue by brianburridge** [Steve998/Assignments#55]
_This is assignment 54 and is due on Mar 19, 2015._
- Download the [RubyKoans](http://rubykoans.com/)
- Create a local git repo and a GitHub repo for them
- Complete 1 - 141 of the Koans
- Check in your work and push to GitHub
- Please provide a link to your new GitHub repo for the Koans

**Comment by Steve998** [comment]
Link 

https://github.com/Steve998/assignment-54-Koans

**Comment by brianburridge** [comment]
:+1:
