### ISSUE TITLE
Sending Email

### ISSUE THREAD

**Issue by brianburridge** [Steve998/Assignments#57]
_This is assignment 55 and is due on Mar 24, 2015._
- Read the Rails guide on [Action Mailer](http://guides.rubyonrails.org/action_mailer_basics.html)
- Add a welcome mailer to the sign up process in your Pinterest app
- Get it working on your laptop first, using the [letter_opener gem](https://github.com/ryanb/letter_opener)
  https://devcenter.heroku.com/articles/sendgrid#ruby-rails
- Next, deploy to Heroku and setup with sendgrid
- Ensure emails are being received by users when signing up on Heroku

**Comment by Steve998** [comment]
I have the email working in the Recipe app. Both the local and the SendGrid in Heroku are working

**Comment by brianburridge** [comment]
@Steve998 Note, that the text version of your mailer won't be included because it's name does not match (welcome vs welcome_email).

**Comment by brianburridge** [comment]
I suggest fixing that, but all other email functionality is working to fulfill this assignment.
