### ISSUE TITLE
jQuery

### ISSUE THREAD

**Issue by brianburridge** [Steve998/Assignments#60]
_This is assignment 59 and is due on Mar 26, 2015._
- Add a [jQuery plugin](http://plugins.jquery.com/) to your Pinterest app
- Be sure to direct me to where on your app you've added it, both in your code and what page it's running on at Heroku so I can see it work.

**Comment by Steve998** [comment]
git link 
https://github.com/Steve998/assignment44-Restrict-Active-Admin-user
heroku link
https://mighty-beyond-3271.herokuapp.com/

Note: if the selection box does not display properly, refresh the browser

Location of select box: Home Page --> Customer button --> New Customer --> Company field
On the home page select the Customer button. In Customer section select the New Customer link at the bottom of the records listing. In the New Customer screen there is a field to enter Company. The Chosen plugin is activated on this pull down list. 
If the selection box does not display properly, refresh the browser.

**Comment by brianburridge** [comment]
@Steve998 if you make the change we talked about this morning to address Turbolinks, then this will work all the time. I'd like to see you do that, and, to fix the button/a hrefs per the comment I just posted in Slack. Once you have those two done, mark this complete again and I'll close out.

**Comment by Steve998** [comment]
I removed the Turbo Link
Also re-did the buttons using the bootstrap
Thanks

heroku link 
https://mighty-beyond-3271.herokuapp.com/
git hub link 
https://github.com/Steve998/assignment44-Restrict-Active-Admin-user

**Comment by brianburridge** [comment]
Removing turbolinks is one way to do it, but then your entire app gets slower. Best in the future to leave turbolinks in your app, but use the `page:change` event instead of document ready, to trigger the chosen script to run.

:+1:
