### ISSUE TITLE
Creating Variables and Literals

### ISSUE THREAD

**Issue by brianburridge** [Steve998/Assignments#7]
_This assignment is due on Jan 28, 2015._
- Create code for each comment in [this gist](https://gist.github.com/brianburridge/79de494772daf7976ea9)
- Run the code and paste the output into your issue as a comment for this assignment
- It should list all the proper class names and all class tests should result in 'true'
- Before you run it, can you guess what will happen with the constant code you've created?

**Comment by Steve998** [comment]
https://gist.github.com/Steve998/c374b91e8f283c78b883

**Comment by Steve998** [comment]
https://gist.github.com/Steve998/286fd2b646adab6fe94f

**Comment by Steve998** [comment]
https://gist.github.com/Steve998/a8f56b0fd7e51d968490
