### ISSUE TITLE
Working with Loops

### ISSUE THREAD

**Issue by brianburridge** [Steve998/Assignments#8]
_This assignment is due on Jan 29, 2015._
- Request input of a number from the user.
- Iterate the number of times indicated by the input number
- Within the loop, print the number of the iteration
- Do this for each of these methods of looping: while, for i in rage, loop, until, .times with counter, until, range
- All should print from 1 to the number input by the user

**Comment by Steve998** [comment]
pushed files to github

**Comment by brianburridge** [comment]
@Steve998 are you sure? I don't see any files here: https://github.com/Steve998/Assignments

**Comment by brianburridge** [comment]
It would be good to clean up your code a bit. Remove the code that is commented out, and ensure everything is properly indented, including comments.

:+1:
